// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frimessage.proto

#include "frimessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR FRIContent::FRIContent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.angles_)*/{}
  , /*decltype(_impl_.external_torques_)*/{}
  , /*decltype(_impl_.measured_torques_)*/{}
  , /*decltype(_impl_.number_of_links_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FRIContentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FRIContentDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FRIContentDefaultTypeInternal() {}
  union {
    FRIContent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FRIContentDefaultTypeInternal _FRIContent_default_instance_;
static ::_pb::Metadata file_level_metadata_frimessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_frimessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_frimessage_2eproto = nullptr;

const uint32_t TableStruct_frimessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::FRIContent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::FRIContent, _impl_.number_of_links_),
  PROTOBUF_FIELD_OFFSET(::FRIContent, _impl_.angles_),
  PROTOBUF_FIELD_OFFSET(::FRIContent, _impl_.external_torques_),
  PROTOBUF_FIELD_OFFSET(::FRIContent, _impl_.measured_torques_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::FRIContent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_FRIContent_default_instance_._instance,
};

const char descriptor_table_protodef_frimessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020frimessage.proto\"i\n\nFRIContent\022\027\n\017numb"
  "er_of_links\030\001 \001(\r\022\016\n\006angles\030\002 \003(\001\022\030\n\020ext"
  "ernal_torques\030\003 \003(\001\022\030\n\020measured_torques\030"
  "\004 \003(\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_frimessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_frimessage_2eproto = {
    false, false, 133, descriptor_table_protodef_frimessage_2eproto,
    "frimessage.proto",
    &descriptor_table_frimessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_frimessage_2eproto::offsets,
    file_level_metadata_frimessage_2eproto, file_level_enum_descriptors_frimessage_2eproto,
    file_level_service_descriptors_frimessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_frimessage_2eproto_getter() {
  return &descriptor_table_frimessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_frimessage_2eproto(&descriptor_table_frimessage_2eproto);

// ===================================================================

class FRIContent::_Internal {
 public:
};

FRIContent::FRIContent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:FRIContent)
}
FRIContent::FRIContent(const FRIContent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FRIContent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.angles_){from._impl_.angles_}
    , decltype(_impl_.external_torques_){from._impl_.external_torques_}
    , decltype(_impl_.measured_torques_){from._impl_.measured_torques_}
    , decltype(_impl_.number_of_links_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.number_of_links_ = from._impl_.number_of_links_;
  // @@protoc_insertion_point(copy_constructor:FRIContent)
}

inline void FRIContent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.angles_){arena}
    , decltype(_impl_.external_torques_){arena}
    , decltype(_impl_.measured_torques_){arena}
    , decltype(_impl_.number_of_links_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FRIContent::~FRIContent() {
  // @@protoc_insertion_point(destructor:FRIContent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FRIContent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.angles_.~RepeatedField();
  _impl_.external_torques_.~RepeatedField();
  _impl_.measured_torques_.~RepeatedField();
}

void FRIContent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FRIContent::Clear() {
// @@protoc_insertion_point(message_clear_start:FRIContent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.angles_.Clear();
  _impl_.external_torques_.Clear();
  _impl_.measured_torques_.Clear();
  _impl_.number_of_links_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FRIContent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 number_of_links = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.number_of_links_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double angles = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_angles(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 17) {
          _internal_add_angles(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double external_torques = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_external_torques(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 25) {
          _internal_add_external_torques(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double measured_torques = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_measured_torques(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 33) {
          _internal_add_measured_torques(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FRIContent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FRIContent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 number_of_links = 1;
  if (this->_internal_number_of_links() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_number_of_links(), target);
  }

  // repeated double angles = 2;
  if (this->_internal_angles_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_angles(), target);
  }

  // repeated double external_torques = 3;
  if (this->_internal_external_torques_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_external_torques(), target);
  }

  // repeated double measured_torques = 4;
  if (this->_internal_measured_torques_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_measured_torques(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FRIContent)
  return target;
}

size_t FRIContent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FRIContent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double angles = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_angles_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double external_torques = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_external_torques_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double measured_torques = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_measured_torques_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // uint32 number_of_links = 1;
  if (this->_internal_number_of_links() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_number_of_links());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FRIContent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FRIContent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FRIContent::GetClassData() const { return &_class_data_; }


void FRIContent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FRIContent*>(&to_msg);
  auto& from = static_cast<const FRIContent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FRIContent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.angles_.MergeFrom(from._impl_.angles_);
  _this->_impl_.external_torques_.MergeFrom(from._impl_.external_torques_);
  _this->_impl_.measured_torques_.MergeFrom(from._impl_.measured_torques_);
  if (from._internal_number_of_links() != 0) {
    _this->_internal_set_number_of_links(from._internal_number_of_links());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FRIContent::CopyFrom(const FRIContent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FRIContent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FRIContent::IsInitialized() const {
  return true;
}

void FRIContent::InternalSwap(FRIContent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.angles_.InternalSwap(&other->_impl_.angles_);
  _impl_.external_torques_.InternalSwap(&other->_impl_.external_torques_);
  _impl_.measured_torques_.InternalSwap(&other->_impl_.measured_torques_);
  swap(_impl_.number_of_links_, other->_impl_.number_of_links_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FRIContent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_frimessage_2eproto_getter, &descriptor_table_frimessage_2eproto_once,
      file_level_metadata_frimessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::FRIContent*
Arena::CreateMaybeMessage< ::FRIContent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FRIContent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
