#ifndef CURAN_UIDEFINITIONS_HEADER_FILE_
#define CURAN_UIDEFINITIONS_HEADER_FILE_

#define GLFW_INCLUDE_VULKAN

#include <GLFW/glfw3.h>

#include <vulkan/vulkan.h>

#define SK_VULKAN
#include "include\core\SkBitmap.h"
#include "include\core\SkBlendMode.h"
#include "include\core\SkBlurTypes.h"
#include "include\core\SkCanvas.h"
#include "include\core\SkCanvasVirtualEnforcer.h"
#include "include\core\SkColor.h"
#include "include\core\SkColorFilter.h"
#include "include\core\SkEncodedImageFormat.h"
#include "include\core\SkFont.h"
#include "include\core\SkFontArguments.h"
#include "include\core\SkFontMetrics.h"
#include "include\core\SkFontMgr.h"
#include "include\core\SkFontParameters.h"
#include "include\core\SkFontStyle.h"
#include "include\core\SkFontTypes.h"
#include "include\core\SkGraphics.h"
#include "include\core\SkImage.h"
#include "include\core\SkImageEncoder.h"
#include "include\core\SkImageFilter.h"
#include "include\core\SkImageGenerator.h"
#include "include\core\SkImageInfo.h"
#include "include\core\SkM44.h"
#include "include\core\SkMallocPixelRef.h"
#include "include\core\SkMaskFilter.h"
#include "include\core\SkMath.h"
#include "include\core\SkMatrix.h"
#include "include\core\SkMilestone.h"
#include "include\core\SkOverdrawCanvas.h"
#include "include\core\SkPaint.h"
#include "include\core\SkPath.h"
#include "include\core\SkPathBuilder.h"
#include "include\core\SkPathEffect.h"
#include "include\core\SkPathMeasure.h"
#include "include\core\SkPicture.h"
#include "include\core\SkPictureRecorder.h"
#include "include\core\SkPixelRef.h"
#include "include\core\SkPixmap.h"
#include "include\core\SkPngChunkReader.h"
#include "include\core\SkPoint.h"
#include "include\core\SkPoint3.h"
#include "include\core\SkPromiseImageTexture.h"
#include "include\core\SkRRect.h"
#include "include\core\SkRSXform.h"
#include "include\core\SkRasterHandleAllocator.h"
#include "include\core\SkRect.h"
#include "include\core\SkRefCnt.h"
#include "include\core\SkRegion.h"
#include "include\core\SkScalar.h"
#include "include\core\SkSerialProcs.h"
#include "include\core\SkShader.h"
#include "include\core\SkSize.h"
#include "include\core\SkStream.h"
#include "include\core\SkString.h"
#include "include\core\SkStrokeRec.h"
#include "include\core\SkSurface.h"
#include "include\core\SkSurfaceCharacterization.h"
#include "include\core\SkSurfaceProps.h"
#include "include\core\SkSwizzle.h"
#include "include\core\SkTextBlob.h"
#include "include\core\SkTime.h"
#include "include\core\SkTraceMemoryDump.h"
#include "include\core\SkTypeface.h"
#include "include\core\SkTypes.h"
#include "include\core\SkUnPreMultiply.h"
#include "include\core\SkVertices.h"
#include "include\core\SkYUVAInfo.h"
#include "include\core\SkYUVAPixmaps.h"
#include "include\docs\SkPDFDocument.h"
#include "include\docs\SkXPSDocument.h"
#include "include\effects\Sk1DPathEffect.h"
#include "include\effects\Sk2DPathEffect.h"
#include "include\effects\SkBlurMaskFilter.h"
#include "include\effects\SkColorMatrix.h"
#include "include\effects\SkColorMatrixFilter.h"
#include "include\effects\SkCornerPathEffect.h"
#include "include\effects\SkDashPathEffect.h"
#include "include\effects\SkDiscretePathEffect.h"
#include "include\effects\SkGradientShader.h"
#include "include\effects\SkHighContrastFilter.h"
#include "include\effects\SkImageFilters.h"
#include "include\effects\SkOverdrawColorFilter.h"
#include "include\effects\SkRuntimeEffect.h"
#include "include\effects\SkShaderMaskFilter.h"
#include "include\effects\SkTableColorFilter.h"
#include "include\effects\SkTableMaskFilter.h"
#include "include\encode\SkJpegEncoder.h"
#include "include\gpu\GrBackendDrawableInfo.h"
#include "include\gpu\GrBackendSemaphore.h"
#include "include\gpu\GrBackendSurface.h"
#include "include\gpu\GrBackendSurfaceMutableState.h"
#include "include\gpu\GrConfig.h"
#include "include\gpu\GrContextOptions.h"
#include "include\gpu\GrContextThreadSafeProxy.h"
#include "include\gpu\GrDirectContext.h"
#include "include\gpu\GrDriverBugWorkarounds.h"
#include "include\gpu\GrRecordingContext.h"
#include "include\gpu\GrTypes.h"
#include "include\gpu\GrYUVABackendTextures.h"
#include "include\gpu\vk\GrVkBackendContext.h"
#include "include\gpu\vk\GrVkExtensions.h"
#include "include\gpu\vk\GrVkMemoryAllocator.h"
#include "include\gpu\vk\GrVkTypes.h"
#include "include\gpu\vk\GrVkVulkan.h"
#include "include\pathops\SkPathOps.h"
#include "include\ports\SkTypeface_win.h"

constexpr auto DEFAULT_TEXT_SIZE = 15.0;
constexpr auto DEFAULT_FRAME_DELAY = std::chrono::milliseconds(15);
constexpr SkScalar VOLUME_PREVIEW_HEIGHT = 200.0f;
constexpr SkScalar VOLUME_PREVIEW_WIDTH = 150.0f;
constexpr SkScalar VOLUME_IMAGE_HEIGHT = 170.0f;
constexpr SkScalar VOLUME_PREVIEW_EXTREMA_SPACING_COLUNM = 20.f;
constexpr SkScalar VOLUME_PREVIEW_EXTREMA_SPACING_LINE = 20.0f;
constexpr int NUMBER_BYTES_PER_PIXEL = 4;
constexpr SkScalar TASK_PREVIEW_HEIGHT = 150.0f;
constexpr SkScalar MANIPULATOR_BAR_HEIGHT = 50;
constexpr SkScalar RADIO_BUTTON_DIMENSION = 20;

#endif