name: hosted-ninja-vcpkg-install-cacheoff
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:

      - name: Install system libraries on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - uses: lukka/get-cmake@latest
      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Setup vcpkg on linux
        if: matrix.os == 'ubuntu-latest'
        run: |
             '${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh'

      - name: Setup vcpkg on windows
        if: matrix.os == 'windows-latest'
        run: |
             '${{github.workspace}}/vcpkg/bootstrap-vcpkg.bat'

      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'Release'
          buildPreset: 'Release'

      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash